/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CheckinDAO;
import dao.UserDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Checkin;
import model.User1;

/**
 *
 * @author Admin
 */
public class CheckinFrm extends javax.swing.JFrame {

    /**
     * Creates new form HomeReaderFrm
     */
    private User1 user;
    private Checkin checkin;
    public CheckinFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        resetCheckin();
        labelSearch.setOpaque(true);
        labelCheck.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        labelSearch = new javax.swing.JLabel();
        labelCheck = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        textSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        labelId_x = new javax.swing.JLabel();
        labelName_x = new javax.swing.JLabel();
        labelPhone_x = new javax.swing.JLabel();
        labelEmail_x = new javax.swing.JLabel();
        labelAddress_x = new javax.swing.JLabel();
        labelDate_x = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        buttonCheckin = new javax.swing.JButton();
        buttonCheckout = new javax.swing.JButton();
        labelId_x1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Đăng nhập");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        labelSearch.setBackground(new java.awt.Color(0, 102, 0));
        labelSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSearch.setForeground(new java.awt.Color(255, 255, 255));
        labelSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSearch.setText("TÌM KIẾM SÁCH");
        labelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSearchMouseExited(evt);
            }
        });

        labelCheck.setBackground(new java.awt.Color(0, 102, 0));
        labelCheck.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCheck.setForeground(new java.awt.Color(255, 255, 255));
        labelCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCheck.setText("VÀO / RA");
        labelCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCheckMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCheckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCheckMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
            .addComponent(labelCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(labelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(login)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Checkin / Checkout");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Mã bạn đọc");

        buttonSearch.setBackground(new java.awt.Color(0, 102, 0));
        buttonSearch.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonSearch.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearch.setText("Tìm kiếm");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        labelId_x.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelId_x.setText("Mã bạn đọc");

        labelName_x.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelName_x.setText("Tên bạn đọc");

        labelPhone_x.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelPhone_x.setText("Số điện thoại");

        labelEmail_x.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelEmail_x.setText("Email");

        labelAddress_x.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelAddress_x.setText("Địa chỉ");

        labelDate_x.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelDate_x.setText("Ngày đăng kí");

        labelPhone.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        labelPhone.setText("jLabel2");

        labelId.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        labelId.setText("jLabel2");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        labelEmail.setText("jLabel2");

        labelName.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        labelName.setText("jLabel2");

        labelDate.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        labelDate.setText("jLabel2");

        labelAddress.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        labelAddress.setText("jLabel2");

        buttonCheckin.setBackground(new java.awt.Color(0, 102, 0));
        buttonCheckin.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonCheckin.setForeground(new java.awt.Color(255, 255, 255));
        buttonCheckin.setText("Checkin");
        buttonCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckinActionPerformed(evt);
            }
        });

        buttonCheckout.setBackground(new java.awt.Color(0, 102, 0));
        buttonCheckout.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonCheckout.setForeground(new java.awt.Color(255, 255, 255));
        buttonCheckout.setText("Checkout");
        buttonCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckoutActionPerformed(evt);
            }
        });

        labelId_x1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelId_x1.setForeground(new java.awt.Color(0, 102, 0));
        labelId_x1.setText("Thông tin bạn đọc");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(labelId_x1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(buttonCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(buttonCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPhone_x)
                                    .addComponent(labelAddress_x)
                                    .addComponent(labelName_x))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelEmail_x)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelId_x)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelDate_x)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(labelId_x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId_x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDate_x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName_x)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhone_x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail_x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddress_x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        LoginFrm frm = new LoginFrm();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_loginMouseClicked

    private void labelCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCheckMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_labelCheckMouseClicked

    private void labelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSearchMouseEntered
        // TODO add your handling code here:
        labelSearch.setBackground(new Color(0, 255, 0));
    }//GEN-LAST:event_labelSearchMouseEntered

    private void labelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSearchMouseExited
        // TODO add your handling code here
        labelSearch.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_labelSearchMouseExited

    private void labelCheckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCheckMouseEntered
        // TODO add your handling code here:
        labelCheck.setBackground(new Color(0, 255, 0));
    }//GEN-LAST:event_labelCheckMouseEntered

    private void labelCheckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCheckMouseExited
        // TODO add your handling code here:
        labelCheck.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_labelCheckMouseExited

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        // TODO add your handling code here:
        login.setForeground(new Color(0, 255, 0));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        // TODO add your handling code here:
        login.setForeground(Color.WHITE);
    }//GEN-LAST:event_loginMouseExited

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        String key = textSearch.getText();
        if(key.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập tên sách!");
        }
        else {
            try {
                User1 u = new UserDAO().getUserByUserId(key);
                if(u == null){
                    JOptionPane.showMessageDialog(rootPane, "Không tồn tại người dùng!");
                }
                else {
                    this.user = u;
                    labelAddress.setVisible(true);
                    labelAddress.setText(u.getAddress());
                    labelAddress_x.setVisible(true);
                    
                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                    if(u.getDate() != null){
                        labelDate.setVisible(true);
                        labelDate_x.setVisible(true);
                        labelDate.setText(dateFormat.format(u.getDate()));
                    }
                    
                    labelEmail.setVisible(true);
                    labelEmail.setText(u.getEmail());
                    labelEmail_x.setVisible(true);
                    
                    labelId.setVisible(true);
                    labelId.setText(u.getUserid());
                    labelId_x.setVisible(true);
                    
                    labelName.setVisible(true);
                    labelName.setText(u.getFullname());
                    labelName_x.setVisible(true);
                    
                    labelPhone.setVisible(true);
                    labelPhone.setText(u.getPhone());
                    labelPhone_x.setVisible(true);
                    
                    Checkin c = new CheckinDAO().checkUserByCheckin(u.getId());
                    this.checkin = c;
                    if(c == null || c.getEnd() != null){
                        buttonCheckin.setVisible(true);
                    }
                    else {
                        buttonCheckout.setVisible(true);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(CheckinFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void buttonCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckinActionPerformed
        // TODO add your handling code here:
        Date currentDate = new Date();
        Timestamp startTimestamp = new Timestamp(currentDate.getTime());
        try {
            new CheckinDAO().insertCheckin(this.user.getId(), startTimestamp);
            this.user = null;
            resetCheckin();
        } catch (SQLException ex) {
            Logger.getLogger(CheckinFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonCheckinActionPerformed

    private void buttonCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckoutActionPerformed
        // TODO add your handling code here:
        Date currentDate = new Date();
        Timestamp endTimestamp = new Timestamp(currentDate.getTime());
        try {
            new CheckinDAO().updateCheckin(this.checkin.getId(), endTimestamp);
            this.user = null;
            this.checkin = null;
            resetCheckin();
        } catch (SQLException ex) {
            Logger.getLogger(CheckinFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCheckoutActionPerformed

    private void labelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSearchMouseClicked
        // TODO add your handling code here:
        SearchBookFrm frm = new SearchBookFrm();
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_labelSearchMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeReaderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeReaderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeReaderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeReaderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeReaderFrm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCheckin;
    private javax.swing.JButton buttonCheckout;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelAddress_x;
    private javax.swing.JLabel labelCheck;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDate_x;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmail_x;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelId_x;
    private javax.swing.JLabel labelId_x1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelName_x;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelPhone_x;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JLabel login;
    private javax.swing.JTextField textSearch;
    // End of variables declaration//GEN-END:variables

    private void resetCheckin() {
        buttonCheckin.setVisible(false);
        buttonCheckout.setVisible(false);
        labelAddress.setVisible(false);
        labelAddress_x.setVisible(false);
        labelDate.setVisible(false);
        labelDate_x.setVisible(false);
        labelEmail.setVisible(false);
        labelEmail_x.setVisible(false);
        labelId.setVisible(false);
        labelId_x.setVisible(false);
        labelName.setVisible(false);
        labelName_x.setVisible(false);
        labelPhone.setVisible(false);
        labelPhone_x.setVisible(false);
        textSearch.setText("");
    }

}
